server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: pos123

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: true

  jackson:
    time-zone: America/Sao_Paulo
    deserialization:
      accept-float-as-int: false